export const DEFAULT_COUNTDOWN_INPUT = '00:25:00'
export const DEFAULT_POMODORO_INPUT = '00:25:00'
export const DEFAULT_POMODORO_BREAK_INPUT = '00:05:00'
export const DEFAULT_POMODORO_SESSIONS = '4'
export const DEFAULT_SOUND_VOLUME = 30
